### ISSUE TITLE
Why not move this to a hook?

### ISSUE THREAD

**Issue by landtax** [jGottschalkGitHub/sinatra-app#1]
We can use before_save for setting these values. We can update modified_at every time a model is saved. We can update created_at only the first time it is saved (created) What do you think?

https://github.com/jGottschalkGitHub/sinatra-app/blob/1d1705e4446ad3ee2e3ac275120a58ac800afd8e/models/list.rb#L19

**Comment by jGottschalkGitHub** [comment]
Implemented for list.rb and item.rb !
Thanks for the tip! :)
